name: dqmc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++

    steps:
      - name: Add oneAPI to apt
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
        
      - name: Install Intel oneAPI
        run: sudo apt-get install intel-oneapi-mkl-devel
      
      - name: Setup Intel oneAPI environment
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV

      - name: Install OpenMPI
        run: |
          sudo apt-get install openmpi-bin
          sudo apt-get install openmpi-doc
          
      - name: Install Boost
        run: sudo apt-get install libboost-all-dev
      
      - name: Install Eigen3
        run: |
          wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
          tar -zxvf eigen-3.4.0.tar.gz
          mkdir eigen-3.4.0/build && cd eigen-3.4.0/build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
          sudo make install
      
      - name: Checkout project code
        uses: actions/checkout@v3

      - name: Build project with CMake
        run: |
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}} && make

      - name: Show helping messages
        run: ${{github.workspace}}/build/dqmc --help

      - name: Run dqmc simulation
        run: |
          mpirun -np 4 --oversubscribe ${{github.workspace}}/build/dqmc --config ${{github.workspace}}/example/config.toml
      
